spring:
    application:
        name: JMonkey-Auth
    profiles:
        active: dev
    redis:
        host: ${JMonkey.redis.host}
        port: ${JMonkey.redis.port}
        database: ${JMonkey.redis.database}

server:
    port: 8101

eureka:
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 20
    client:
        serviceUrl:
            defaultZone: http://${JMonkey.eureka.userName}:${JMonkey.eureka.password}@${JMonkey.eureka.host}:${JMonkey.eureka.port}/eureka

ribbon:
    eager-load:
        clients: JMonkey-Modules-UPMS
        enabled: true
    httpclient:
        enabled: false
    OkHttp:
        enabled: true
    ReadTimeout: 30000
    ConnectTimeout: 30000
feign:
    hystrix:
        enabled: true
    okhttp:
        enabled: true
    httpclient:
        enabled: false
    client:
        config:
            feignName:
                connectTimeout: 30000
                readTimeout: 30000
    compression:
        request:
            enabled: true
        response:
            enabled: true
hystrix:
    threadpool:
        default:
            coreSize: 500
            maxQueueSize: 1000
            queueSizeRejectionThreshold: 800
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

logging:
    config: classpath:logback.xml

JMonkey:
    urls:
        anon:
            - /signin
            - /signup
            - /jmonkey/auth/**
    auth:
        clientId: JMonkey_client_id
        clientSecret: JMonkey_client_secret
        scope: server
    token:
        expiresIn: 3600 # token过期时间，默认10小时，单位秒，60 * 60（一小时）

