JMonkey:
    eureka:
        userName: JMonkey
        password: 123456
        host: localhost
        port: 8100
    dataSource:
        userName: root
        password: 123456
        url: jdbc:mysql://114.116.89.11:3306/hjw_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    redis:
        host: 114.116.89.11
        port: 6379
        database: 15

