spring:
    application:
        name: JMonkey-Gateway
    profiles:
        active: dev
    redis:
        host: ${JMonkey.redis.host}
        port: ${JMonkey.redis.port}
        database: ${JMonkey.redis.database}

server:
    port: 8088

zuul:
    ignoredServices: '*'
    host:
        connect-timeout-millis: 30000
        socket-timeout-millis: 30000
    routes:
        auth:
            path: /jmonkey/auth/**
            serviceId: JMonkey-Auth
        upms:
            path: /jmonkey/upms/**
            serviceId: JMonkey-Modules-UPMS

ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 30000

eureka:
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 20
    client:
        serviceUrl:
            defaultZone: http://${JMonkey.eureka.userName}:${JMonkey.eureka.password}@${JMonkey.eureka.host}:${JMonkey.eureka.port}/eureka

security:
    validate:
        code: true
        preview: false
    sessions: stateless
    oauth2:
        resource:
            loadBalanced: true
            token-info-uri:http: ${JMonkey.tokenUrl}/oauth/check-token
            service-id: JMonkey-Gateway
            jwt:
                key-uri: ${JMonkey.tokenUrl}/oauth/token_key #解析jwt令牌所需要密钥的地址
        client:
            accessTokenUri: ${JMonkey.tokenUrl}/oauth/token
            userAuthorizationUri: ${JMonkey.tokenUrl}/auth/oauth/authorize
            clientId: JMonkey_client_id
            clientSecret: JMonkey_client_secret
JMonkey:
    urls:
        anon:
            - /signin
            - /signup
            - /jmonkey/auth/**
            - /jmonkey/upms/code/**
            - /jmonkey/upms/**
