spring:
    application:
        name: JMonkey-Gateway
    profiles:
        active: dev
    redis:
        host: 114.116.89.11
        port: 6379
        database: 15

server:
    port: 8088

zuul:
    ignoredServices: '*'
    host:
        connect-timeout-millis: 30000
        socket-timeout-millis: 30000
    routes:
        auth:
            path: /jmonkey/auth/**
            serviceId: JMonkey-Auth
        upms:
            path: /jmonkey/upms/**
            serviceId: JMonkey-Modules-UPMS

eureka:
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 20
    client:
        serviceUrl:
            defaultZone: http://${JMonkey.eureka.userName}:${JMonkey.eureka.password}@${JMonkey.eureka.host}:${JMonkey.eureka.port}/eureka

JMonkey:
    urls:
        anon:
            - /signin
            - /signup
            - /jmonkey/auth/**
