JMonkey:
    eureka:
        userName: JMonkey
        password: 123456
        host: localhost
        port: 8100
    tokenUrl: http://localhost:8101
    redis:
        host: 114.116.89.11
        port: 6379
        database: 15
    baseUrl: /jmonkey
    fileTempMemory: D://fileTempMemory
